### ISSUE TITLE
New Rule Proposal: Disallow multiple empty lines

### ISSUE THREAD

**Issue by another-dave** [sasstools/sass-lint#1015]
Hello,

I'd like to propose a rule to disallow multiple consecutive empty lines in a file. E.g.:

```scss
/* Allowed */
.foo {
    margin: 5px;
}

.bar {
    padding: 10px;
}

/* Disallowed */
.foo {
    margin: 5px;
}



.bar {
    padding: 10px;
}

```

For JavaScript, we're using ESLint's [no-multiple-empty-lines](http://eslint.org/docs/rules/no-multiple-empty-lines) rule which allows for:

* Max number of allowed consecutive empty lines.
* Separate max configurable for start & end of files.

I'd be happy to try and submit a PR / test cases for same, but wanted to first check if it sounded like a feature others would want to.

Please let me know if I can give more relevant details.

Thanks!
Dave
