### ISSUE TITLE
Error in terminal following what seems to be a successful linting operation

### ISSUE THREAD

**Issue by afholderman** [sasstools/sass-lint#1057]
I run my sass-lint command and get a list of errors but at the end get an error, details below.

**What version of Sass Lint are you using?** 
1.10.2

**Please include any relevant parts of your configuration**
sass-lint.yml

```
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  max-warnings: 0
# File Options
files:
  include: 'stye/scss/**/*.s+(a|c)ss'
  ignore:
    - 'style/scss/variables.scss'
    - 'node_modules/**/*'

```

**What did you do? Please include the actual source code causing the issue.** 
Ran `sass-lint -config .sass-lint.yml './style/scss/**/*.scss' -verbose -no-exit`

**What did you expect to happen?** 
Linting with no error

**What actually happened? Please include any error messages given to you by Sass Lint.**
Got the following error in the terminal:
```
/Users/aholderman/Sites/devdesktop/manifest-dev/docroot/themes/manifest/node_modules/sass-lint/index.js:313
    throw new exceptions.SassLintFailureError(errorCount.count + ' errors were detected in \n- ' + errorCount.files.join('\n- '));
    ^
Error
    at Function.sassLint.failOnError (/Users/aholderman/Sites/devdesktop/manifest-dev/docroot/themes/manifest/node_modules/sass-lint/index.js:313:11)
    at detectPattern (/Users/aholderman/Sites/devdesktop/manifest-dev/docroot/themes/manifest/node_modules/sass-lint/bin/sass-lint.js:31:10)
    at /Users/aholderman/Sites/devdesktop/manifest-dev/docroot/themes/manifest/node_modules/sass-lint/bin/sass-lint.js:83:5
    at Array.forEach (native)
    at Object.<anonymous> (/Users/aholderman/Sites/devdesktop/manifest-dev/docroot/themes/manifest/node_modules/sass-lint/bin/sass-lint.js:82:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
