### ISSUE TITLE
Output lint report even on success

### ISSUE THREAD

**Issue by justinhough** [sasstools/sass-lint#1058]
Is there a way to output the sass-lint report even when everything comes back as a success? 

I am trying to compile a few lint tools together to generate a clean report that shows all checks have passed successfully but noticed that `sass-lint` doesn't write the report again when all warnings and errors have returned a success. So basically it will always show the last warning or error reported before they were fixed. It would be great if there is a way to force the output even on success.

What version of Sass Lint are you using?
1.10.2

I am running the following CLI command with a configuration file: `sass-lint -c .sass-lint.yml -v`

Config file:
```
files:
  include: 'src/styles/**/*.scss'
options:
  formatter: json
  merge-default-rules: false
  output-file: 'linters/sass-lint.json'
```
