### ISSUE TITLE
Enforce mixin and extend order

### ISSUE THREAD

**Issue by tomspeak** [sasstools/sass-lint#1064]
Would it be possible to implement the same functionality brought in by `property-sort-order` but for `mixin-sort-order` and `placeholder-sort-order`?

We have a list of media query mixins:

```scss
.block {
    color: red;

    @include media('>phone') {
        color: blue;
    }

    @include media('>tablet') {
        color: purple;
    }

    @include media('>desktop') {
        color: lightsalmon;
    }
}
```

And would like to enforce that they are declared with mobile first in mind.
