### ISSUE TITLE
indentation validation does not work for comments that are above a definition

### ISSUE THREAD

**Issue by akrillo89** [sasstools/sass-lint#1072]
Hey,

right now the comments have issues with line indentation validation. For example when I use the linter for the following definition:

![image](https://cloud.githubusercontent.com/assets/2676770/26103612/a1c00f9a-3a3a-11e7-9c24-aa8e749ba81e.png)

I get an issue in line 14. It's best practice to put a comment above a definition to avoid long lines.

I am using sass lint via command line and in visual code. Both have the same error.

sass-lint version: 1.10.2

.sass-lint.yml

```
#########################
## Sample Sass Lint File
#########################
# File Options
files:
  include: 'sass/**/*.s+(a|c)ss'
# Rule Configuration
rules:
  class-name-format:
    - 1
    -
      convention: '^([\.\%]?[a-zA-Z]*[-]?[a-zA-Z0-9\-]*)(\.[a-zA-Z0-9\-]*)?(__[a-zA-Z0-9]*[-]?[a-zA-Z0-9\-]*)?(--[a-zA-Z0-9]*[-]?[a-zA-Z0-9\-]*)?(\:[a-z]*)*$'
      convention-explanation: 'Class should be written in BEM (Block Element Modifier) syntax.'
  no-duplicate-properties: 2
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - respond-to

  no-warn: 1
  no-debug: 1
  no-ids: 1
  no-important: 2
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    order: 'alphabetical'
    ignore-custom-properties: true
  variable-for-property:
    - 2
    -
      properties:
        - color
        - background-color
        - box-shadow

```
