### ISSUE TITLE
Allow custom ignore regex in class-name-format

### ISSUE THREAD

**Issue by atomicpages** [sasstools/sass-lint#1097]
Enhancement Request:

* Adding custom ignore regular expression support for `class-name-format` rule

Sometimes we override TPL styles to suit our needs and often time, we can't change these selectors. Luckily, many TPLs provide _prefixes_ we can grab on to via regex.

```scss
.myAppPrefix {
  color: red;

  .nested {
    height: 10px;
  }
}

.myAppPrefix__ele {
  color: red;
}
```

We can configure `sass-lint` as follows to suit our needs:

```js
'class-name-format': [1, { ignore: /^myAppPrefix.*/ }]
```

I have implemented this. The solution can be seen here: https://github.com/atomicpages/sass-lint/commit/a11aabff9d8989f46144998c5b45b0c530a5cfe5
