### ISSUE TITLE
nesting-depth:max-depth doesn't work

### ISSUE THREAD

**Issue by Deimoslink** [sasstools/sass-lint#1100]
nesting-depth rule doesn't work if max-depth is more than 2.

What version of Sass Lint are you using?
```
sass-lint -V
1.10.2

```
Please include any relevant parts of your configuration
```
options:
  merge-default-rules: false

rules:
  nesting-depth:
    - 2
    -
      max-depth: 3
```

What did you do? Please include the actual source code causing the issue.
`sass-lint -c sass-lint-rules.yml -v -q`

What did you expect to happen?
I expect to have an output

What actually happened? Please include any error messages given to you by Sass Lint.
No output at all
It happens when I set max-depth to more than 2.

If you're using a IDE plugin have you tried the CLI too?
I am using CLI.

Moreover, I don't have any output in case there are no warnings at all.
Therefore, I can switch to max-depth: 2 and I will have warnings and the output would be created.
But it doesn't work with max-depth: 3, 4 and so on.
