### ISSUE TITLE
misspelled-properties change in 1.11.0 breaks nested properties

### ISSUE THREAD

**Issue by christianrank** [sasstools/sass-lint#1112]
**Used version**: 1.11.0

```scss
@mixin font-test1 {
  font: {
    family: Arial, sans-serif;
    style: normal;
    weight: 300;
  }
}

@mixin font-test2 {
  font: {
    family: Arial, sans-serif;
    style: normal;
    weight: 400;
  }
}
```

results in the following error:

```  13:5  error  Property `weight` appears to be spelled incorrectly  no-misspelled-properties```

It's also weird that it only complains about the second `weight`, if there's only one mixin, it doesn't complain at all.

**Expected**: There shouldn't be an error.
