### ISSUE TITLE
Comment warning

### ISSUE THREAD

**Issue by cmckni3** [sasstools/sass-lint#1136]
What version of Sass Lint are you using? 1.11.1

What did you do? Please include the actual source code causing the issue.

```scss
.next-month {
    /*!
    /*rtl:begin:ignore*//*
    */
    right: 0;
    /*!
    /*rtl:end:ignore*//*
    */
}
```

What did you expect to happen? I would like to see a warning. It might not be possible. I know it's a developer error but would be nice to detect.

What actually happened? No errors or warnings. Styles following it in the compiled css are commented out.

If you're using a IDE plugin have you tried the CLI too? Using CLI and Visual Studio Code.
