### ISSUE TITLE
Not possible to igonre -webkit-tap-highlight-color property for no-vendor-prefixes rule

### ISSUE THREAD

**Issue by skripnike** [sasstools/sass-lint#1188]
gulp-sass-lint: 1.3.4

.sass-lint.yml:
```
no-vendor-prefixes: 1
    - ignore-non-standard: true
    - excluded-identifiers: ['-webkit-tap-highlight-color']
```
I want to ignore `-webkit-tap-highlight-color` property for `no-vendor-prefixes` rule, but

https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-vendor-prefixes.md#ignore-non-standard
herer exist article how to Ignore Non Standard, but not working because **`tap-highlight-color` exist in default property list** https://github.com/sasstools/sass-lint/blob/master/data/properties.yml

`excluded-identifiers: ['-webkit-tap-highlight-color']` do not work aswell possible only ignore all webkit properies:
```
no-vendor-prefixes: 1
    - excluded-identifiers: ['webkit']
```

only helped to remove `tap-highlight-color` from `/node_modules/ssas-lint/data/properties.yml` and use `ignore-non-standard: true`

Does exist anly possible way to ignore specified property? `-webkit-tap-highlight-color` for example.

**Comment by coreyward** [comment]
I'm similarly experiencing that the `ignore-non-standard` option on the `no-vendor-prefixes` rule doesn't behave as [described in the docs](https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-vendor-prefixes.md): 

```yaml
# .sass-lint.yml
options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
rules:
  no-vendor-prefixes:
    - 1
    -
      ignore-non-standard: true
```

```scss
$black: #111;
body {
  -webkit-font-smoothing: antialiased;
  -webkit-tap-highlight-color: $black;
}
```

Running `sass-lint` spits out the following:
```
   3:3   warning  Vendor prefixes should not be used                                             no-vendor-prefixes
   4:3   warning  Vendor prefixes should not be used                                             no-vendor-prefixes
```
