### ISSUE TITLE
Removal of semi-colon, Variable usage before declaration in Sass partials

### ISSUE THREAD

**Issue by johnnyraper** [sasstools/sass-lint#1221]
Hi,

I am running sass-lint version 1.12.1 and am experiencing some bizarre issues in the output of my `*.scss` files. While the `property-sort-order` is working, there are two issues described below:

**Issue 1**

_Before Linting:_

```scss
@mixin heading-properties($font-family, $font-size, $line-height, $letter-spacing: -1px) {
  margin: $grid-spacing 0 $grid-spacing-3x;
  font: {
    family: $font-family;
    size: $font-size;
  }
  line-height: $line-height;
  text-transform: uppercase;
  letter-spacing: $letter-spacing;
}
```

_After Linting:_

```scss
@mixin heading-properties($font-family, $font-size, $line-height, $letter-spacing: -1px) {
  margin: $grid-spacing 0 $grid-spacing-3x;
  letter-spacing: $letter-spacing
  text-transform: uppercase;
  line-height: $line-height;
  font: {
    size: $font-size;
    family: $font-family;
  };
}
```

The semi-colon has been removed after `$letter-spacing`. At first I thought that this was because it was a variable, but it seems that this isn't the case.

**Issue 2**

_Before Linting:_

```scss
span.label {
      $font-size: mat-font-size($custom-typography, body-1);
      $indicator-offset: $grid-spacing;

      // Set a width bigger than the label could possibly be,
      // and use this to vertically centre it to the markers
      $width: $font-size * 5;

      display: inline-block;
      position: absolute;
      left: -$width / 2;
      @if $position == 'top' {
        top: -$indicator-offset - $font-size;
      } @else {
        top: $indicator-diameter + $indicator-offset;
      }
      width: $width;
      font-size: $font-size;
      line-height: 1;
      text-align: center;
      text-transform: uppercase;
    }
```

_After Linting:_

```scss
span.label {
      $indicator-offset: $grid-spacing;
      $width: $font-size * 5;

      $font-size: mat-font-size($custom-typography, body-1);

      display: inline-block;
      left: -$width / 2;
      text-transform: uppercase;
      @if $position == 'top' {
        top: -$indicator-offset - $font-size;
      } @else {
        top: $indicator-diameter + $indicator-offset;
      }
      text-align: center;
      line-height: 1;
      font-size: $font-size;
      width: $width;
      position: absolute;
    }
```

The line: `$width: $font-size * 5;` has been moved above the declaration: `$font-size: mat-font-size($custom-typography, body-1);`

I'm not sure why the semi-colon is being removed. I'm also not sure why the library would move the usage of a declaration before its declaration.

I would appreciate any help in resolving these issues. Many thanks.

Best,
Johnny
