### ISSUE TITLE
property-sort-order throws when css variables are in use

### ISSUE THREAD

**Issue by justinanastos** [sasstools/sass-lint#1224]
What version of Sass Lint are you using?

>1.12.1

Please include any relevant parts of your configuration

```yaml
# .sass-lint.yml
files:
  include: 'dummy.scss'
rules:
  property-sort-order: 2
```

What did you do? Please include the actual source code causing the issue.

>Ran the linter with the following file:

```scss
/* dummy.scss */
.test-class {
    --css-variable: 1px;
}
```

What did you expect to happen?

>Expected the linter to not fail

What actually happened? Please include any error messages given to you by Sass Lint.

>Error was thrown and linter exited with error code.

```
Cannot read property 'first' of null
```

The error originates from https://github.com/sasstools/sass-lint/blob/develop/lib/rules/property-sort-order.js#L103 because there are no 'property' nodes for a css variable (there is `customProperty` instead).

If you're using a IDE plugin have you tried the CLI too?

>No

# Suggested course of action

Exit early if `var prop = dec.first('property')` doesn't find anything
