### ISSUE TITLE
[ie] hack *vertical-align: middle; breaks the linter

### ISSUE THREAD

**Issue by englishextra** [sasstools/sass-lint#1239]
```css
// sass-lint:disable-all
.col input[type^="text"],
.col input[type^="search"],
.col input[type^="email"],
.col input[type^="url"],
.col input[type^="password"],
.col input[type^="tel"],
.col input[type^="color"],
.col input[type^="number"],
.col input[type^="date"],
.col input[type^="month"],
.col input[type^="week"],
.col input[type^="time"],
.col input[type^="datetime"],
.col input[type^="datetime-local"],
.col select,
.col textarea {
	font-size: 14px;
	line-height: 20px;
	box-sizing: border-box;
	vertical-align: baseline;
	*vertical-align: middle;
	-webkit-tap-highlight-color: transparent;
	outline: none;
	padding: 0 8px;
}
// sass-lint:enable-all
```
CMD.exe output
```bash
// sass-lint:disable-all
.col input[type^="text"],
.col input[type^="search"],
.col input[type^="email"],
.col input[type^="url"],
.col input[type^="password"],
.col input[type^="tel"],
.col input[type^="color"],
.col input[type^="number"],
.col input[type^="date"],
.col input[type^="month"],
.col input[type^="week"],
.col input[type^="time"],
.col input[type^="datetime"],
.col input[type^="datetime-local"],
.col select,
.col textarea {
	font-size: 14px;
	line-height: 20px;
	box-sizing: border-box;
	vertical-align: baseline;
	*vertical-align: middle;
	-webkit-tap-highlight-color: transparent;
	outline: none;
	padding: 0 8px;
}
// sass-lint:enable-all
```
