### ISSUE TITLE
Allow css vars in rgba(), and other color functions

### ISSUE THREAD

**Issue by nwpappas** [sasstools/sass-lint#1249]
Request to allow the `no-color-literals` rule to accept css `var()` statements.

```yml
no-color-literals:
  - 1
  - allow-css-variables: true
```

Would allow:

```scss
.background {
  background-color: rgba(var(--my-background-rgb), var(--my-background-alpha));
}
```
