### ISSUE TITLE
Mixins Before Declarations

### ISSUE THREAD

**Issue by WuglyakBolgoink** [sasstools/sass-lint#1260]
Can not understand this error:

![image](https://user-images.githubusercontent.com/2271337/52915306-8eb10e80-32d2-11e9-9788-fe94f615f223.png)

1) mixin's was written before we use it in class... 
2) Should we write `@include FontLight;` as last element in class?

> https://github.com/sasstools/sass-lint/blob/develop/docs/rules/mixins-before-declarations.md

**Comment by katsun0921** [comment]
You write @include FontLight;  as first element in class.

```scss
@font-face {
  @include FontLight;

  font-family: "Barlow";
}
```
