### ISSUE TITLE
Ignored file still being processed

### ISSUE THREAD

**Issue by mven** [sasstools/sass-lint#129]
`sass-lint -v -i tests/sass/border-zero.scss tests/sass/*.scss`

This results in border-zero.scss being processed still.

**Comment by damianleung** [comment]
I have the same result if I use a sass-lint.yml, it's seems to just ignore the ignore rule. A file in assets/sass/vendor/ still gives me errors.

``` 
/node_modules/sass-lint/lib/groot.js:21
    throw new Error('Parsing error' + fileInfo + ': ' + e.message);
```

```
# File Options
files:
  include: 'assets/sass/**/*.scss'
  ignore:
    - 'assets/sass/vendor/**/*.*'
```
