### ISSUE TITLE
Bug: indentation plugin throws type error

### ISSUE THREAD

**Issue by skovhus** [sasstools/sass-lint#134]
Linting a file like this with 1.2.0 (using tabs instead of space):
```scss
@include keyframes(anim-1) {
	from {
		margin-left: 100px;
	}

	50% {
		margin-left: 200px;
	}

	to {
		margin-left: 100px;
	}
}
```

Throws an error: 
```
/usr/local/lib/node_modules/sass-lint/lib/rules/indentation.js:52
                  'line': node.content[i + 1].start.line,

TypeError: Cannot read property 'start' of undefined
    at processNode (/usr/local/lib/node_modules/sass-lint/lib/rules/indentation.js:52:46)
    at processNode (/usr/local/lib/node_modules/sass-lint/lib/rules/indentation.js:77:9)
```
