### ISSUE TITLE
New Rule: Mergeable Selector

### ISSUE THREAD

**Issue by Snugug** [sasstools/sass-lint#18]
Check to see if selectors can be merged together

**Comment by DanPurdy** [comment]
Nearly, done with this. 

Few interesting points I was reading within the `scss-lint` issues

First off - one I'm intending to support
[mergeable-selector whitelist](https://github.com/brigade/scss-lint/issues/540)

And a few cases we need to be careful with.. Adding lots of tests
[avoid this](https://github.com/brigade/scss-lint/issues/520)

**Comment by DanPurdy** [comment]
@Snugug @bgriffith Wondering if you guys have opinions on the following?

The force nesting option within the mergeable selectors rule of scss-lint allows you to force element nesting as such

```scss
div p {
  color: red;
}

// to this

div {
  p {
    color: red;
  }
}
```

But it doesn't enforce pseudo class nesting like the following

```scss
div:hover {
  color: red;
}

// Not enforced

div {
  &:hover {
    color: red;
  }
}
```

I think it's a valid type of nesting to flag up and so I'm thinking as well as the whitelist option I already have working we should perhaps support both a force nesting option and a force pseudo nesting option.

I think a separate rule for each may be a little overboard but it makes `mergeable-selector` fairly flexible..

I'm just trying to cover this in tests for all types of selectors too
