### ISSUE TITLE
Feature blocks-no-empty-line

### ISSUE THREAD

**Issue by zallek** [sasstools/sass-lint#231]
Hi,

I have a feature proposition: a rule to disallow empty lines in blocks.

The following would raise an error:
```CSS
.comment {
  display: flex;

  padding: 20px;
}
```
