### ISSUE TITLE
New Rule: detect properties conflict

### ISSUE THREAD

**Issue by zallek** [sasstools/sass-lint#237]
Hi, It would be great to have a rule to detect properties conflicts.

Example:
The following would raise an error. As `float: left` has no effect on a flex item.
```CSS
.comment {
  display: flex;
  float: left;
}
```

Would be great to find an exhaustive list of css properties conflicts.
