### ISSUE TITLE
New Rule: Duplicate Property

### ISSUE THREAD

**Issue by Snugug** [sasstools/sass-lint#28]
As Per [SCSS Lint](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#duplicateproperty)

**Comment by bgriffith** [comment]
Will take a look at this one today.

**Comment by bgriffith** [comment]
Any opinions on whether this should trigger when using both long hand and short hand properties?

Should the following trigger an error?
```scss
.foo {
  margin-left: 10px;
  padding: 0;
  margin: 0;
}
```
