### ISSUE TITLE
no-duplicate-properties should allow repeat properties when they are directly next to each other

### ISSUE THREAD

**Issue by BPScott** [sasstools/sass-lint#280]
Duplicating properties is sometimes required - such as when providing fallbacks for unsupported features, e.g. the following is a legitimate usage but currently raises a warning:

```scss
.foo {
  display: inline-block;
  display: flex;
}
```

Sass-lint should follow [CSSLint's lead](https://github.com/CSSLint/csslint/wiki/Disallow-duplicate-properties) and allow duplicate properties when they have different values but are immediately next to each other. I.e. the following are warnings:

```scss
/* properties with the same value */
.mybox {
  border: 1px solid black;
  border: 1px solid black;
}

/* properties separated by another property */
.mybox {
  border: 1px solid black;
  color: green;
  border: 1px solid red;
}
```

But the following should be acceptable, and not raise a warning:

```scss
/* one after another with different values */
.mybox {
  border: 1px solid black;
  border: 1px solid red;
}
```
