### ISSUE TITLE
empty-line-between-blocks should have an option to ignore single line blocks

### ISSUE THREAD

**Issue by BPScott** [sasstools/sass-lint#282]
Sometimes when writing many short blocks where there is a single property (/ mixin / extend) per block it is useful to group them close to each other as they are often inherently related. For instance a set of width classes can be densely packed instead of having a blank line between each class:

```scss
.w1-of-12 { width: (1/12) * 100%; }
.w2-of-12 { width: (2/12) * 100%; }
.w3-of-12 { width: (3/12) * 100%; }
.w4-of-12 { width: (4/12) * 100%; }
.w5-of-12 { width: (5/12) * 100%; }
.w6-of-12 { width: (6/12) * 100%; }
.w7-of-12 { width: (7/12) * 100%; }
.w8-of-12 { width: (8/12) * 100%; }
.w9-of-12 { width: (9/12) * 100%; }
.w10-of-12 { width: (10/12) * 100%; }
.w11-of-12 { width: (11/12) * 100%; }
.w12-of-12 { width: (12/12) * 100%; }
```

[Scss-lint's empty-line-between-blocks rule](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#emptylinebetweenblocks) allows these single-line rule sets to sit next to each other as it has a configuration option `allow_single_line_rule_sets` that defaults to `true`. The configuration option may be set to off to disallow this exception.

Sass-lint should mimic this behaviour so that I may write the above without raising warnings.
