### ISSUE TITLE
New Rule: Single Line Per Property

### ISSUE THREAD

**Issue by BPScott** [sasstools/sass-lint#283]
Add rule to enforce each property (/ `@include` / `@extends`) within a selector exists on a single line. As per the [existing scss-lint SingleLinePerProperty rule](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#singlelineperproperty).

Allowed:

```scss
p {
  margin: 0;
  padding: 0;
}
```

Disallowed:

```scss
p {
  margin: 0; padding: 0;
}
```

There should be a `allow_single_line_rule_sets` option that defaults to `true` to allow the usage of single-line rule sets, to make the following allowed:

```scss
p { margin: 0; padding: 0; }
```

As an extension to the exisiting functionality I think it could be useful to add an additional configuration option `maxPropertiesForSingleLineRuleSet` to allow users to limit the amount of properties within a single-line ruleset, defaulting to `Infinity`. For instance if `maxPropertiesForSingleLineRuleSet` was set to 1 then `p { margin: 0; padding: 0; }` would be invalid, but `p { margin: 0; }` would be acceptable. This would allow people to limit these single-line rulesets to only be used in cases where the number of properties won't affect readability.
