### ISSUE TITLE
Sass-lint process fails if selector has no space between it and opening brace

### ISSUE THREAD

**Issue by micahgodbolt** [sasstools/sass-lint#301]
The following causes sass-lint to fail and return "Warning: Cannot read property 'type' of undefined Use --force to continue."
```
a{
  background: red;
}
```
But this is fine (space after the a tag)
```
a {
  background: red;
}
```

**Comment by DanPurdy** [comment]
There's something really odd happening here...

```scss
a {
  color: red;
}

.test{ <----
  color: red;
}

.test {
  color: red;
}
```

even a block like that in the middle of a file will cause all the other errors and warnings to disappear..

add the space again or change it to the following and all is fine!
