### ISSUE TITLE
Please create some reasonable config example.

### ISSUE THREAD

**Issue by mik01aj** [sasstools/sass-lint#308]
I copy-pasted [your default config](https://github.com/sasstools/sass-lint/blob/develop/docs/sass-lint.yml), and I suspect that's what pretty much every developer would do.

```
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: html
  # Output file instead of logging results
  output-file: 'linters/sass-lint.html'
```

These options are not what people usually want. Especially [`merge-default-rules`](https://github.com/sasstools/sass-lint/blob/master/docs/options/merge-default-rules.md), which does something very complicated (I did read the doc page and still don't get it), and because of this, effectively, my rule config was ignored (I still got warnings about rules I marked as ignored). This is not the nicest developer experience.

Plus, this is really easy to fix :)
