### ISSUE TITLE
No example on how to use custom property-sort-order or YAML file

### ISSUE THREAD

**Issue by Saturn2888** [sasstools/sass-lint#338]
I would like to see some documentation on how to setup property-sort-order in the YAML file. I have seen none and searching doesn't yield anything conclusive.

**Comment by Saturn2888** [comment]
This is the best I've been able to come up with. There's also some Zen ordering as well. I don't know how this compares. Am I able to put a list of items in the `order` property as well?

```yaml
    property-sort-order:
        - 1
        - order: smacss
```

**Comment by Snugug** [comment]
You can check out our [property sort order docs](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/property-sort-order.md) which inherit our general [rules example](https://github.com/sasstools/sass-lint/tree/develop/docs). You can also see all of the default orders [in our config](https://github.com/sasstools/sass-lint/tree/develop/lib/config/property-sort-orders). This is what setting up [SMACSS sort order looks like](https://github.com/sasstools/sass-lint/blob/develop/lib/config/property-sort-orders/smacss.yml)

**Comment by bgriffith** [comment]
For a custom set the yaml would be:

```yml
property-sort-order:
      - 1
      -
          order:
              - 'position'
              - 'top'
              - 'right'
              - 'bottom'
              - 'left'
              - 'z-index'
              - 'display'
              - 'float'
              - 'width'
              - 'height'
              - 'max-width'
              - 'max-height'
              - 'min-width'
              - 'min-height'
              - 'padding'
              - 'padding-top'
              - 'padding-right'
              - 'padding-bottom'
              - 'padding-left'
              - 'margin'
              - 'margin-top'
              - 'margin-right'
              - 'margin-bottom'
              - 'margin-left'
              - 'margin-collapse'
              - 'margin-top-collapse'
              - 'margin-right-collapse'
              - 'margin-bottom-collapse'
              - 'margin-left-collapse'
              - 'overflow'
              - 'overflow-x'
              - 'overflow-y'
              - 'clip'
              - 'clear'
              - 'font'
              - 'font-family'
              - 'font-size'
              - 'font-smoothing'
              - 'osx-font-smoothing'
              - 'font-style'
              - 'font-weight'
              - 'hyphens'
              - 'src'
              - 'line-height'
              - 'letter-spacing'
              - 'word-spacing'
              - 'color'
              - 'text-align'
              - 'text-decoration'
              - 'text-indent'
              - 'text-overflow'
              - 'text-rendering'
              - 'text-size-adjust'
              - 'text-shadow'
              - 'text-transform'
              - 'word-break'
              - 'word-wrap'
              - 'white-space'
              - 'vertical-align'
              - 'list-style'
              - 'list-style-type'
              - 'list-style-position'
              - 'list-style-image'
              - 'pointer-events'
              - 'cursor'
              - 'background'
              - 'background-attachment'
              - 'background-color'
              - 'background-image'
              - 'background-position'
              - 'background-repeat'
              - 'background-size'
              - 'border'
              - 'border-collapse'
              - 'border-top'
              - 'border-right'
              - 'border-bottom'
              - 'border-left'
              - 'border-color'
              - 'border-image'
              - 'border-top-color'
              - 'border-right-color'
              - 'border-bottom-color'
              - 'border-left-color'
              - 'border-spacing'
              - 'border-style'
              - 'border-top-style'
              - 'border-right-style'
              - 'border-bottom-style'
              - 'border-left-style'
              - 'border-width'
              - 'border-top-width'
              - 'border-right-width'
              - 'border-bottom-width'
              - 'border-left-width'
              - 'border-radius'
              - 'border-top-right-radius'
              - 'border-bottom-right-radius'
              - 'border-bottom-left-radius'
              - 'border-top-left-radius'
              - 'border-radius-topright'
              - 'border-radius-bottomright'
              - 'border-radius-bottomleft'
              - 'border-radius-topleft'
              - 'content'
              - 'quotes'
              - 'outline'
              - 'outline-offset'
              - 'opacity'
              - 'filter'
              - 'visibility'
              - 'size'
              - 'zoom'
              - 'transform'
              - 'box-align'
              - 'box-flex'
              - 'box-orient'
              - 'box-pack'
              - 'box-shadow'
              - 'box-sizing'
              - 'table-layout'
              - 'animation'
              - 'animation-delay'
              - 'animation-duration'
              - 'animation-iteration-count'
              - 'animation-name'
              - 'animation-play-state'
              - 'animation-timing-function'
              - 'animation-fill-mode'
              - 'transition'
              - 'transition-delay'
              - 'transition-duration'
              - 'transition-property'
              - 'transition-timing-function'
              - 'background-clip'
              - 'backface-visibility'
              - 'resize'
              - 'appearance'
              - 'user-select'
              - 'interpolation-mode'
              - 'direction'
              - 'marks'
              - 'page'
              - 'set-link-source'
              - 'unicode-bidi'
              - 'speak'
```
