### ISSUE TITLE
Warnings for nested properties

### ISSUE THREAD

**Issue by claudiopro** [sasstools/sass-lint#352]
This example of nested properties [from the docs](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#nested_properties):

```scss
.funky {
  font: {
    family: fantasy;
    size: 30em;
    weight: bold;
  }
}
```

Produces the following warnings:

```
2:8  warning  Whitespace required before {                         space-before-brace
2:9  warning  Trailing semicolons required                         trailing-semicolon
3:5  warning  Property `family` appears to be spelled incorrectly  no-misspelled-properties
5:5  warning  Property `weight` appears to be spelled incorrectly  no-misspelled-properties
```
