### ISSUE TITLE
Still cannot ignore files in the .yml file

### ISSUE THREAD

**Issue by dgresko** [sasstools/sass-lint#369]
I was very excited about the update to the plugin today, but I still am unable to ignore files in my .yml file. I have a custom .yml, that am successfully pointing to for all of the rules, but it will not ignore the file that I have it set to ignore. I have the following:

```
files:
  include: 'src/*.s+(a|c)ss'
  ignore:
    - 'src/core/styles/_base.scss'
```
I am using gulp-sass-lint to run it. Is this still an issue for anyone else?
Any help is much appreciated.

**Comment by bgriffith** [comment]
Can you check/confirm that you're running 1.3.2? (Found in node_modules/gulp-sass-lint/node_modules/sass-lint/package.json)

I just tried something similar and it worked ok.

```yml
files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - 'tests/sass/zero-unit.scss'
```
