### ISSUE TITLE
Is there a way to skip a line or section from being validated? 

### ISSUE THREAD

**Issue by mitogh** [sasstools/sass-lint#372]
Hi!

I was wondering if there is a way to skip the validation on a block of section for example if I set `no-important: 2` 

Is there a way to skip a code like: 

```scss
.image{
   display: 100% !important;
}
```

Thank you :smile:
