### ISSUE TITLE
shorthand-values rule fails to identify negative values

### ISSUE THREAD

**Issue by alfaproject** [sasstools/sass-lint#375]
As the title says, it seems that `shorthand-values` fails to understand this:
```css
test {
    margin: 8px -8px;
}
```

http://puu.sh/lbuOB/8b1c1cb2e0.png
