### ISSUE TITLE
New Rule: Empty Args

### ISSUE THREAD

**Issue by Snugug** [sasstools/sass-lint#38]
With Sass, if a function or mixin doesn't have any arguments, the parenthesis can be left off of the definition and, in the case of mixins, the invocation as well

**Comment by bgriffith** [comment]
Started to look into this one. Experience is slightly different. Parenthesis can be left off of the definition of mixins but not functions. When I try I get a Sass error;
`@function baz ": expected "(", was "{"`

While I can drop the parenthesis off both the invocation of functions and mixins.

```scss
// Causes an error
@function baz {
  @return 'baz';
}

// Is ok
.baz {
  content: baz;
}

// Is ok
@mixin qux {
  content: 'baz';
}

// Is ok
.qux {
  @include qux;
}
```
