### ISSUE TITLE
@at-root registers as nested depth

### ISSUE THREAD

**Issue by gitnik** [sasstools/sass-lint#383]
```scss
.foo {
    @at-root &__bar {
        @at-root &__baz {
            display: inline-block;
        }
    }
}
```

This registers as a depth of 2 which is technically correct but considering that `@at-root` generates a completely new, unnested selector I think this rule should be disabled in this specific case. I am willing to submit a PR if this behaviour is not wanted anymore.

**Comment by DanPurdy** [comment]
Hi @gitnik I think this makes sense yes, my only worry is that it opens a lot of edge cases around the rule that we'll need to be very careful with. @sasstools/sass-lint-contributors does anyone have any other opinions on this regarding whether we are really linting compiled nest depth or actual nesting depth within the scss/sass files where I would still class the above as nesting depth of 3.

**Comment by gitnik** [comment]
Well I don't really consider this "nesting" since the end result will be everything but nested. But I can see where you're coming from. Looking forward to what other people have to say about this

**Comment by DanPurdy** [comment]
I had another think about this @gitnik I think you're right it should be excluded. Happy for you to get a PR up if you want to.

**Comment by bgriffith** [comment]
Are we saying that the following should be valid? 

```scss
.foo {
@at-root &__bar {
@at-root &__baz {
    display: inline-block;
}
}
}
```
