### ISSUE TITLE
No output with CLI, also wrong line numbers

### ISSUE THREAD

**Issue by itsimoshka** [sasstools/sass-lint#393]
I have `test.sass`:
``` sass
.splash
  bottom: 0
  left: 0
  margin: auto
  position: absolute
  top: 0
  right: 0
```

`.sass-lint`:

``` yml
files:
  include: 'test.sass'
options:
  formatter: html
  merge-default-rules: false
  output-file: 'linter/sass-lint.html'
rules:
  border-zero:
    - 1
    - convention: zero
  brace-style:
    - 1
    - allow-single-line: true
  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 1
  extends-before-declarations: 1
  extends-before-mixins: 1
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1
  function-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  indentation:
    - 1
    - size: 2
```

when I run

    sass-lint 

I have no output. But when I use 

    sass-lint  -v

I get output in `linter/sass-lint.html`
Also it contains:

```
5:1	Warning	Indentation of 0, expected 2	indentation
7:1	Warning	Indentation of 0, expected 2	indentation
9:1	Warning	Indentation of 0, expected 2	indentation
11:1	Warning	Indentation of 0, expected 2	indentation
13:1	Warning	Indentation of 0, expected 2	indentation
```

But why so strange line numbers?
