### ISSUE TITLE
Allow rules as a plugin

### ISSUE THREAD

**Issue by gajus** [sasstools/sass-lint#432]
There appears to be no way to have rules loaded as a plugin.

Ideally, a custom rule should be declared using `plugin-{rule-name}`:

```yml
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  plugin-{rule-name}
```

`sass-lint` in turn would attempt to find a peer dependency called `sass-lint-plugin-{rule-name}`, e.g. I would like to publish rule `sass-lint-plugin-property-sort-order`.
