### ISSUE TITLE
empty-line-between-blocks should support an option to allow one empty line only

### ISSUE THREAD

**Issue by joseluisq** [sasstools/sass-lint#433]
[empty-line-between-blocks](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/empty-line-between-blocks.md) should support an option to **allow one empty line** between blocks.

For example:
```yaml
empty-line-between-blocks:
  - 1
  -
    include: true
    allow-single-line-rulesets: true
```

With above options, several empty lines are allowed:

![captura de pantalla de 2015-11-25 00-54-46](https://cloud.githubusercontent.com/assets/1700322/11389479/3294010e-930f-11e5-8b60-f197cb20e51d.png)

Adding `allow-one-empty-line: true` option:

```yaml
empty-line-between-blocks:
  - 1
  -
    include: true
    allow-single-line-rulesets: true
    allow-one-empty-line: true
```

![captura de pantalla de 2015-11-25 01-05-03](https://cloud.githubusercontent.com/assets/1700322/11389630/99eb22fa-9310-11e5-8c46-e68fde298af6.png)

Of course, this is a proposal option.
Regards.
