### ISSUE TITLE
function-name-format doesn't take exception to built-in CSS functions

### ISSUE THREAD

**Issue by benthemonkey** [sasstools/sass-lint#434]
See the discussion on #344. The rule also needs to have exceptions for the other functions that are part of vanilla CSS.

E.g.
```scss
.class {
    background: linear-gradient(to bottom, rgba(255, 255, 255, 1) 0%, rgba(255, 255, 255, 0) 100%);
}
```

Will throw lint warnings for `linear-gradient`.
