### ISSUE TITLE
space-around-operator incorrectly enforces negative z-index

### ISSUE THREAD

**Issue by Dru89** [sasstools/sass-lint#454]
It looks like `space-around-operator`'s exception handling is missing some cases where negative numbers don't necessarily have a dimension or percentage.  For instance, the following should be valid CSS:

```scss
.foo {
  z-index: -1;
}
```

Unfortunately, it looks like the `space-around-operator` rule expects that `-` to have a space before it.  Putting a space before it actually breaks the AST, though.

**Comment by alfaproject** [comment]
Indeed, noticed this today and was going to report it.

**Comment by Dru89** [comment]
There are some other scenarios where you can run into this, too, like the expression:
```scss
.foo {
  margin: -1 * ($foo + $bar + $baz);
}
```
