### ISSUE TITLE
mixins-before-declarations should be more similar to scss-lint

### ISSUE THREAD

**Issue by benthemonkey** [sasstools/sass-lint#455]
I was playing around with migrating from scss-lint (using my config converter), and frequently rely on the fact that `DeclarationOrder` enforces:
- `@extend` declarations
- `@include` declarations without inner `@content`
- properties
- `@include` declarations with inner `@content`
- nested rule sets

This is especially useful for readability when mixins generate media queries:
```scss
.foo {
    content: "bar";

    @include respond-to(sm) {
        content: "baz";
    }
}
```
