### ISSUE TITLE
Bug: Indentation rule with parens

### ISSUE THREAD

**Issue by bgriffith** [sasstools/sass-lint#46]
Using parens causes an issue with the indentation rule. 

```scss
// Causes an error - 'Indentation of 2, expected 4'
@if (1 == 1) {
  content: 'foo';
}

// Is ok
@if 1 == 1 {
  content: 'foo';
}

// Is ok
@mixin bar($foo) {
  content: 'bar';
}
```

Using v1.0.0
