### ISSUE TITLE
Inline ignore option

### ISSUE THREAD

**Issue by tjbenton** [sasstools/sass-lint#462]
Allow for an inline ignore option like jshint offers. This is very handy to have because there's always special cases where someone can't follow strict standards and being able to add an ignore to them would be nice so you don't have to see those linter errors

```scss
// scss-lint ignore: start
a, label, button,
select, input[type='button'], input[type='reset'],
input[type='submit'], input[type='radio'], input[type='checkbox'] {
  cursor: pointer;
}
// scss-lint ignore: end

input[type='submit'] { // scss-lint ignore: line
  ...
}
```

I looked through the documentation and didn't come across anything like this, so if this option is available would you be able to tell me how to use it.
