### ISSUE TITLE
Various discrepancies to scss-lint (indentation and property ordering)

### ISSUE THREAD

**Issue by stowball** [sasstools/sass-lint#464]
Indentation is much less forgiving in sass-lint when you align code to make it more readable. Take this example:

```scss
.is-expanded {
    opacity: 1;
    z-index: 1;
    height: ($share-services__link-size * $share-services__list-row-count) +
            ($share-services__gutter-size * ($share-services__list-row-count * 2)) +
            ($share-services__toggler-height + $share-services__toggler-margin-bottom) +
            ($share-services__inner-margin * 2) + $share-services__inner-arrow-size;
}
```

will complain that all of the calculations for `height` should be at the same indentation as `height`

---

Using concentric ordering, sass-lint complains about `@font-face` declarations, whereas scss-lint doesn't.

```scss
@font-face {
    font-family: 'Gotham';
    src: url('font-name.eot');
    src: url('font-name.eot?#iefix') format('embedded-opentype'),
         url('font-name.woff2') format('woff2'),
         url('font-name.woff') format('woff'),
         url('font-name.ttf') format('truetype'),
         url('font-name.svg#fontname') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

will result in warning  Expected `font-weight`, found `src`  property-sort-order
