### ISSUE TITLE
How to supress warnings

### ISSUE THREAD

**Issue by aseem2625** [sasstools/sass-lint#473]
Is there any way to supress warnings in this library?
Can someone give me pointer to some resource or example.

Thanks

**Comment by DanPurdy** [comment]
Do you mean lint warnings? How are you using `sass-lint` ? With the CLI?

**Comment by aseem2625** [comment]
Yes, I want to suppress *lint warnings* for some part of my code. 
**E.g.**, in eslint library, I can supress it using **//eslint-disable-line no-console** as a comment in front of the console.log statement. And console.log statements are set to give js lint warnings if encountered anywhere in code. But I use this comment to ignore(suppress) for particular ones.

Similarly, I want to ask if anything exists for sass lint. Because I want hyphenated naming convention in scss file but some library which I am using has camelCasing in some class name and I want to modify this class scss properties. So, I can't avoid using camelCasing, so I want to supress naming convention for only these class names.

I am using it as in CLI
>npm run sass-lint -v 

and then my config file is automatically picked up which in turns selects my scss files and runs lint check on them.

**Comment by BPScott** [comment]
sass-lint currently does not support selectively disabling rules within a file using comments. #70 tracks this issue and there is an open PR for it (#402) so whatch that space.

For your particular issue, the [class-name-format](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/class-name-format.md) rule already has an `ignore` option that lets you specify a whitelist of ignored class names that you know don't match your desired format. Adding them all you your config file might be a bit tedious but it should solve your problem.

**Comment by aseem2625** [comment]
Hi, @BPScott Thanks for the knowledge but I followed the link https://github.com/sasstools/sass-lint/blob/develop/docs/rules/class-name-format.md and couldn't make things work.

Below is the thing I used:
>  function-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
    - ignore: ['classNameA', 'classNameB', 'classNameC']

As it said, we need to array of class names to be ignored. But I tried different possibility of writing class names as **'.classNameA', .classNameA, classNameA** but none of it worked. I mean, still the same warnings are being given for classNameA, classNameB, classNameC in sass lint check.

Can you please help me to know what's the exact syntax.

**Also, I would like to bring in notice, I wrote something like**
>.classNameA tbody td.classNameB:not(.classNameC) {
//my scss properties...
}
**Here, while classNameA and classNameB are identified as being in camelCasing, *but classNameC* goes unoticed in sass lint check. Can be a possible bug**


Thanks

**Comment by benthemonkey** [comment]
Hi @aseem2625,
Here is one correct way to format the settings (using `class-name-format` not `function-name-format`):
```yaml
rules:
  class-name-format:
    - 1
    -
      allow-leading-underscore: true
      convention: hyphenatedlowercase
      ignore:
        - classNameA
        - classNameB
        - classNameC
```

Let me know if that works for you. I tested it locally and it worked for me.

**Comment by aseem2625** [comment]
@benthemonkey 
Hi, this worked for me.
``` 
class-name-format:
    - 1
    - convention: hyphenatedlowercase
      ignore:
        - classNameA
        - classNameB
        - classNameC
        - classNameD
```
Thanks
---------
How to raise issue for below case?

```  
.classNameB tbody td.classNameC:not(.classNameD) {
    width:100%;
    ...
}
```
There is a strange case, where classNameD is not reported in sass lint warnings on running sass lint check, while classNameA, classNameB, classNameC are reported.
 
And interestingly, if I write just classNameB in the ignore as above then I don't have to write classNameC in the ignore. 
(Note: classNameA is independent of this issue because I think issue is only this kind of sass code)

**Comment by benthemonkey** [comment]
`:not(selector)` is a case that isn't accounted for in any of the name format rules at the moment. I'll close this Issue and open a separate one.

Thanks!

**Comment by aseem2625** [comment]
@benthemonkey 
That helps. Thanks :)

**Comment by benthemonkey** [comment]
Either I'm not fully understanding the scenario, or I'm unable to reproduce the issue you are seeing.

SCSS:
```scss
.classNameA td.classNameB {
  .classNameC {
    width: 3px;
  }
}
```

Settings:
```yaml
rules:
  space-around-operator: 1
  class-name-format:
    - 1
    -
      convention: hyphenatedlowercase
      ignore:
        - classNameA
```

I get the expected warnings:
```
  1:16  warning  Class '.classNameB' should be written in lowercase with hyphens  class-name-format
  2:4   warning  Class '.classNameC' should be written in lowercase with hyphens  class-name-format
```

Can you give a case where a wrongly-formatted class selector is ignored?

**Comment by aseem2625** [comment]
@benthemonkey 

Ok, I'll rewrite it.
----
CODE:
```
.classNameB tbody td.classNameC:not(.classNameD) {
    width: 3px;
}
```
my YML 1:
```
class-name-format:
    - 1
    - convention: hyphenatedlowercase
      ignore:
        - classNameB
        - classNameC
        - classNameD
```
Lint check lists classNameB, classNameC. But never lists classNameD(which is **ISSUE 1**)
-----

my YML 2:
class-name-format:
    - 1
    - convention: hyphenatedlowercase
      ignore:
        - classNameB
        - classNameC
```
Lint check doesn't lists classNameB, classNameC.

**ISSUE 2** is.
```
class-name-format:
    - 1
    - convention: hyphenatedlowercase
      ignore:
        - classNameB
```

Now also, 
Lint check doesn't lists classNameB, classNameC. Which means writing classNameB is handling classNameC automatically. I've rechecked again just now.

**Comment by benthemonkey** [comment]
Strangely I'm not observing the same behavior as you. I have changed by SCSS to be the exact same as yours, and Sass Lint is reporting `classNameC`. @DanPurdy do you have any insight here?

**Comment by aseem2625** [comment]
@benthemonkey 
Just to clarify, for your case, classNameC is being reported after writing **just** classNameB in the ignore?

**Comment by benthemonkey** [comment]
Correct.

SCSS:
```scss
.classNameB tbody td.classNameC:not(.classNameD) {
  width: 4px;
}
```

Settings:
```yaml
rules:
  class-name-format:
    - 1
    - convention: hyphenatedlowercase
      ignore:
        - classNameB
```

I get the expected warning:
```
  1:22  warning  Class '.classNameC' should be written in lowercase with hyphens  class-name-format
```

**Comment by benthemonkey** [comment]
I added the entire contents of my files and the command I used.

**Comment by aseem2625** [comment]
@benthemonkey 

Aah, I got the issue

Try writing your YML as 

```
options:
  merge-default-rules: false
files:
  include: tmp.scss
rules:
  class-name-format:
    - 1
    - convention: hyphenatedlowercase
      ignore:
        -classNameB
```

instead of

```
options:
  merge-default-rules: false
files:
  include: tmp.scss
rules:
  class-name-format:
    - 1
    - convention: hyphenatedlowercase
      ignore:
        - classNameB
```


**Note there is no spacing between - and classNameB **
