### ISSUE TITLE
Please add Property Sort Order rules for nested properties

### ISSUE THREAD

**Issue by ethancfchen** [sasstools/sass-lint#494]
When I turn on `order: 'smacss'` setting for `property-sort-order`, I found that it works find with all properties but not the nested properties.
For example, when I have:

``` scss
{
    background-position: top center;
    background-image: map-get($images, bg-index);
    background-repeat: no-repeat;
    background-size: auto 80%;
}
```

I will got warning color just what I wanted, but when I change to:

``` scss
{
  background: {
    position: top center;
    image: map-get($images, bg-index);
    repeat: no-repeat;
    size: auto 80%;
  }
}
```

all warnings are gone, it seems that the `background-position` was recognized to `position`
