### ISSUE TITLE
Bug: One declaration per line has issue with named parameters

### ISSUE THREAD

**Issue by bgriffith** [sasstools/sass-lint#51]
Named parameters cause issue with one declaration per line. Best example for these are the [Other color functions](http://sass-lang.com/documentation/Sass/Script/Functions.html#other_color_functions) with their optional parameters

The following tests currently fail:
```scss 

// The following all cause issues
$foo: adjust-color(rgb(255, 0, 0), $lightness: -20%);

.bar {
  color: adjust-color(#102030, $blue: 5);
  background-color: scale-color(hsl(120, 70%, 80%), $lightness: 50%);
  border-color: change-color(hsl(25, 100%, 80%), $lightness: 40%, $alpha: 0.8);
}
```

Using v1.0.0
