### ISSUE TITLE
Dynamic placeholders causes a fatal error

### ISSUE THREAD

**Issue by ngryman** [sasstools/sass-lint#532]
Hi,

Dynamic placeholder names are reported as fatal errors when declared but not when they are extended.
I'm using `sass-lint 1.5.0`.

Code example:
```scss
// produces an error
%#{$placeholder-id} { color: red; }
// but the following is ok
'%#{$placeholder-id}' { color: red; }

// this does not produce an error
@extend %#{$placeholder-id};
```
