### ISSUE TITLE
Indentation rule doesn't like alignment in multiline structures

### ISSUE THREAD

**Issue by Lexicality** [sasstools/sass-lint#591]
In structures such as
```scss
#loading-screen {
    // Magic animations
    visibility: hidden;
    transform: translateX(-100%);
    // Delay the visibility until we've drifted out
    transition: transform $in-out-speed,
                visibility 0s $in-out-speed;
    transition-timing-function: linear;
}
```
or
```scss
@font-face {
    font-family: "Freight Sans Pro";
    src: url("../fonts/FreightSansProMedium.woff") format("woff"),
         url("../fonts/FreightSansProMedium.ttf")  format("truetype");
}
```
scss-lint 1.5.1 complains about the overflow line's indentation:
```
error-pages/_fonts.scss
  4:10  error  Indentation of 9, expected 4  indentation
```
The only way to appease it is to reduce the overhanging line to the base indentation of the block
```scss
{
    src: url("../fonts/FreightSansProMedium.woff") format("woff"),
    url("../fonts/FreightSansProMedium.ttf")  format("truetype");
}
```
or put it all on one line
```scss
{
    transition: transform $in-out-speed, visibility 0s $in-out-speed;
}
```
neither of which I am happy with.
