### ISSUE TITLE
Exclude code block with comments

### ISSUE THREAD

**Issue by ncoden** [sasstools/sass-lint#600]
I think it can be usefull to exclude a block code for one or all rules with comments. Sometimes I want to bypass a rule for browser compatibility reasons, but without disabling this rule for the whole project.

We can do like eslint :
```scss
// Disable one or all rules on a whole selector or property group

// sass-lint-disable {rule name}
.foo { ... }
// sass-lint-enable {rule name}
```
```scss
// Disable one or all rules on a single property

.foo {
  property: value;
  property: value; // sass-lint-disable {rule name}
  property: value; // sass-lint-ignore {rule name}
}
```

But personally I don't like to see `sass-lint` inside by code. I prefer something like (we can purpose both).
```scss
.foo {
  property: value;
  property: value; // hack
  property: value; // !hack
}
```

What do you think ?
