### ISSUE TITLE
Placeholder name format doesn't ignore variables

### ISSUE THREAD

**Issue by bgriffith** [sasstools/sass-lint#625]
Current the `placeholder-name-format` rule will incorrectly flag up variables.
```scss
$var: 'foo';

%#{$var} {
  font-size: 18px;
}
```

Will incorrectly return `Placeholder %#{$var} should be written in lowercase with hyphens`.

Sass 1.5.1, develop branch
