### ISSUE TITLE
element:state ~ element element - throw fatal

### ISSUE THREAD

**Issue by Igloczek** [sasstools/sass-lint#633]
This code works fine:
```scss
input:focus ~ ul {
    background: #ff0000;
}
```
This throws a fatal:
```scss
input:focus ~ ul li {
    background: #ff0000;
}
```
