### ISSUE TITLE
Keyframes parsing issue?

### ISSUE THREAD

**Issue by scottbert** [sasstools/sass-lint#642]
Just upgraded from sass-lint 1.5.1 to 1.6.2
```scss
@keyframes liquid-tube {
  0% {    // Line 1165
    opacity: 0;
    transform: scale(1, 1);
  }

  10% {
    opacity: 1;
    transform: scale(1, 1);
  }

  50%, 100% {
    opacity: 1;
    transform: scale(1, 0);
  }
}
```
"sass-lint Error Fatal Please check validity of the block starting from line #1165". Seems like there may be a bug? Appears to be the case in 1.6.0 and 1.6.1 too.
