### ISSUE TITLE
[ENHANCEMENT REQUEST] - Quote attribute values in selectors

### ISSUE THREAD

**Issue by egaudette** [sasstools/sass-lint#707]
This request is for the enforcement of quotation of attributes in selectors, as such:

**Example(s) of enforcement:**
default enforcement:
```yaml
attribute-quotes: 2
```
explicit enforcement:
```yaml
  attribute-quotes:
    - 2
    -
      include: true;
```

The following would be allowed:

```scss
input[type="checkbox"] {
    color: #aaa;
}
```

The following would be disallowed:
```scss
input[type=checkbox] {
    color: #aaa;
}
```

<br/>
<br/>

**Example(s) of non-enforcement:**
default non-enforcement:
```yaml
attribute-quotes: 0
```
explicit non-enforcement:
```yaml
  attribute-quotes:
    - 0
    -
      include: false;
```

The following would be allowed:

```scss
input[type=checkbox] {
    color: #aaa;
}
```

The following would be disallowed:
```scss
input[type="checkbox"] {
    color: #aaa;
}
```
