### ISSUE TITLE
Interpolation broken (again?)

### ISSUE THREAD

**Issue by pixelass** [sasstools/sass-lint#819]
String interpolations cause sass-lint to fail. Due to this issue I have to disable sass-lint entirely.

* "sass-lint": "1.8.2"

* default config as in example

```scss
.#{$prefix}-0 {
    display: none;
}
```

* The selector should be resolved

* Instead I get an error

```shell
57:1  error  Please check validity of the block starting from line #57  Fatal
```

I used CLI
