### ISSUE TITLE
Add support for indentation continuation options

### ISSUE THREAD

**Issue by alfaproject** [sasstools/sass-lint#838]
I was wondering if there are plans to support more indentation options, specially multiline definitions like the example bellow. Having everything in one line is not exactly readable, and creating inline exceptions (in the future) will look spammy.

What version of Sass Lint are you using?

```
node sass-lint.js --version
1.9.0
```

Please include any relevant parts of your configuration

``` yaml
  indentation:
    - 2
    -
      size: 4
```

What did you do? Please include the actual source code causing the issue.

``` scss
.btn-danger {
    box-shadow:
        0 1px 1px rgba(0, 0, 0, .5),
        inset 0 1px 0 rgba(250, 255, 255, .4);
}
```

What did you expect to happen?
No errors thrown.

What actually happened? Please include any error messages given to you by Sass Lint.
Indentation error: https://puu.sh/qLQsP/38875e3e1a.png

If you're using a IDE plugin have you tried the CLI too?
I'm using the Atom plugin, but same thing happens on CLI.
