### ISSUE TITLE
ignore-non-standard does not ignore -webkit-tap-highlight-color

### ISSUE THREAD

**Issue by PinPinIre** [sasstools/sass-lint#843]
What version of Sass Lint are you using?
1.9.0

Please include any relevant parts of your configuration

``` YAML
rules:
  no-vendor-prefixes:
    - 2
    -
      ignore-non-standard: true
```

``` SCSS
html {
  -webkit-tap-highlight-color: $link-color-hover;
}

button::-moz-focus-inner,
input::-moz-focus-inner {
  border: 0;
  padding: 0;
}

input[type="number"]::-webkit-inner-spin-button,
input[type="number"]::-webkit-outer-spin-button {
  height: auto;
}
```

What did you do? Please include the actual source code causing the issue.
I ran the no-vendor-prefixes rule on the example for `ignore-non-standard` which then caused an error. If the `ignore-non-standard` config is set to false, 5 errors are thrown which is expected.

What did you expect to happen?
The -webkit-tap-highlight-color property to be ignored when `ignore-non-standard: true`.

What actually happened? Please include any error messages given to you by Sass Lint.
An error was thrown.
The -webkit-tap-highlight-color property caused an error to be thrown.
`2:3    Error   Vendor prefixes should not be used  no-vendor-prefixes`

If you're using a IDE plugin have you tried the CLI too?
The above occurred using the CLI.
