### ISSUE TITLE
The no-mergeable-selectors rule makes a bad suggestion

### ISSUE THREAD

**Issue by chrismbarr** [sasstools/sass-lint#858]
I am using the current version of `gulp-sass-lint`

I have this code 
```scss
.is-sticky {
	//Add this class when an element is stuck to the page
	&:not(.no-sticky-shadow) {
		//A class could be added to prevent this shadow from being added
		box-shadow: $shadow-z-2;
	}

	&:not(.card) {
		//Only add these for non-cards
		background-color: $card-bg;
		padding: $spacing $spacing-small 0 $spacing-small;
	}
}
```

Which produces this error
```
Rule `.is-sticky &:not(null)` should be merged with the rule on line 152
```

I don't understand why or how those rules could be merged, and it's apparently not even parsing these rules correctly due to the `null` being in there.  My guess it that it parses each of these rules as `:not(null)` which makes it appear they are the same selector and could be merged.

**Comment by DanPurdy** [comment]
Yeah, it's a bug. I'll look into it, it's not reading the content inside the parenthesis correctly. I thought i'd caught all cases of this but obviously not. Sorry!

**Comment by chrismbarr** [comment]
In the meantime I was able to add this to my configuration to ignore this false positive

```yml
no-mergeable-selectors:
    - 1
    -
      'whitelist':
        - '.is-sticky &:not(null)'
```
