### ISSUE TITLE
Idea: add a ignore-properties option to the no-vendor-prefixes rule

### ISSUE THREAD

**Issue by chrismbarr** [sasstools/sass-lint#868]
I am using version `1.9.1` and am currently affected by issue #843 regarding the `ignore-non-standard` option not working, but that gave me an idea for a new option/setting to add to the `no-vendor-prefixes` rule.

Right now when`ignore-non-standard` is `true` it just ignores all properties that aren't listed in the [standard properties list](https://github.com/sasstools/sass-lint/blob/master/data/properties.yml), but IMO this can be too leniant in some cases.  Instead I'd love to have the ability to just list out the non-standard properties that I want to allow in my application, instead of just allowing them all.

An example configuration for this might look like this

``` yml
  no-vendor-prefixes:
    - 1
    -
      'ignore-properties':
        - '-ms-overflow-style'
        - '-ms-touch-action'
        - '-webkit-font-smoothing'
        - '-webkit-tap-highlight-color'
        - '-webkit-overflow-scrolling'
        -'::-webkit-scrollbar'
        -'::-webkit-scrollbar-button'
        -'::-webkit-scrollbar-track'
        -'::-webkit-scrollbar-thumb'
```

If this option were added my application could ONLY use these vendor prefixes, and not any others.  Since so many developers at my organization might touch this code, this really helps limit the kinds of styles they might add.  Since we use `autoprefixer` it's not needed for a developer to add any vendor prefixes except for the instances listed above.
