### ISSUE TITLE
Error with rules/space-before-colon:17 previous.is('space') cannot read property 'is'

### ISSUE THREAD

**Issue by Glutnix** [sasstools/sass-lint#878]
What version of Sass Lint are you using?
sass-lint 1.9.1
node 6.6

Please include any relevant parts of your configuration

This was converted from a scss-lint.yml file using the converter.
```yaml
# sass-lint config generated by make-sass-lint-config v0.1.2
#
# The following scss-lint Linters are not yet supported by sass-lint:
# ElsePlacement, SelectorDepth, SpaceAfterComment, UnnecessaryParentReference
# VendorPrefixes
#
# The following settings/values are unsupported by sass-lint:
# Linter Indentation, option "character"
# Linter SpaceBeforeBrace, option "allow_single_line_padding"

files:
  include:
  - 'resources/assets/sass/**/*.s+css'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero: 1
  brace-style:
    - 1
    - allow-single-line: false
  class-name-format:
    - 0
    - convention: hyphenatedbem
  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: false
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 1
    - include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 0
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  id-name-format:
    - 0
    - convention: hyphenatedbem
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 1
    - include: true
  mixin-name-format:
    - 0
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations: 1
  nesting-depth:
    - 1
    - max-depth: 6
  no-color-keywords: 1
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 0
  no-empty-rulesets: 1
  no-ids: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 0
  no-misspelled-properties:
    - 1
    - extra-properties: []
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 1
  no-url-protocols: 0
  placeholder-in-extend: 1
  placeholder-name-format:
    - 0
    - convention: hyphenatedbem
  property-sort-order:
    - 0
    - ignore-custom-properties: false
  quotes:
    - 1
    - style: single
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-bang:
    - 1
    - include: false
  space-after-colon:
    - 1
    - include: true
  space-after-comma: 1
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 1
  variable-name-format:
    - 0
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit: 1
```
What did you do? Please include the actual source code causing the issue.
ran `sass-lint` from the command line

What did you expect to happen?
To run without node error

What actually happened? Please include any error messages given to you by Sass Lint.
```
PROJECT_FOLDER/node_modules/sass-lint/lib/rules/space-before-colon.js:17
        if (previous.is('space')) {
                    ^

TypeError: Cannot read property 'is' of undefined
    at Node.<anonymous> (PROJECT_FOLDER/node_modules/sass-lint/lib/rules/space-before-colon
    .js:17:21)
    at PROJECT_FOLDER/node_modules/gonzales-pe/lib/gonzales.js:305:54
    at Node.traverse (PROJECT_FOLDER/node_modules/gonzales-pe/lib/gonzales.js:279:6)
    at Node.traverse (PROJECT_FOLDER/node_modules/gonzales-pe/lib/gonzales.js:284:36)
    at Node.traverse (PROJECT_FOLDER/node_modules/gonzales-pe/lib/gonzales.js:284:36)
    at Node.traverse (PROJECT_FOLDER/node_modules/gonzales-pe/lib/gonzales.js:284:36)
    at Node.traverse (PROJECT_FOLDER/node_modules/gonzales-pe/lib/gonzales.js:284:36)
    at Node.traverseByTypes (PROJECT_FOLDER/node_modules/gonzales-pe/lib/gonzales.js:304:11)
    at Object.detect (PROJECT_FOLDER/node_modules/sass-lint/lib/rules/space-before-colon.js:13:9)
    at PROJECT_FOLDER/node_modules/sass-lint/index.js:124:27
```
