### ISSUE TITLE
alpha ordering differs that of scss-lint

### ISSUE THREAD

**Issue by mmase** [sasstools/sass-lint#899]
We are trying to move over to sass-lint from https://github.com/brigade/scss-lint. The config moved over nicely, except alphabetical means browser specific properties at end of property list instead of inline.

Example:

scss-lint accepts the following as alphabeticalized:

```scss
div {
  height: 31px;
  line-height: 29px;
  padding: 0 15px;
  -moz-user-select: none;
  -webkit-user-select: none;
  user-select: none;
  vertical-align: middle;
  white-space: nowrap;
}}
```

sass-lint wants:

```scss
div {
  height: 31px;
  line-height: 29px;
  padding: 0 15px;
  user-select: none;
  vertical-align: middle;
  white-space: nowrap;
  -moz-user-select: none;
  -webkit-user-select: none;
}
```

Is there a workaround for this without having to modify all the sass?
