### ISSUE TITLE
variable name format bug

### ISSUE THREAD

**Issue by mmase** [sasstools/sass-lint#901]
The following throws a warning for variable name format, when it shouldn't (likely due to no spaces between variable name and operator):

```scss
.content-main {
  padding: $mobile-site-gutter*1.5;
}
```
