### ISSUE TITLE
Enforce font-family stack ending with generic font family keyword fallback 

### ISSUE THREAD

**Issue by DrummerHead** [sasstools/sass-lint#919]
For example, if you have a class declaration block like:

``` css
.example {
  font-family: Palatino, Georgia;
}
```

Throw an error enforcing a generic font family keyword at the end of the stack (`serif`, `sans-serif`, `monospace`, `cursive`, `fantasy`)

Thanks!
