### ISSUE TITLE
Keyframes parsing issue with commas

### ISSUE THREAD

**Issue by megawac** [sasstools/sass-lint#942]
What version of Sass Lint are you using?

1.10.1

Please include any relevant parts of your configuration

```scss
@keyframes example {
  0% {
    transform: translate(-50%, 50%);
  },
  100% {
    transform: translate(-50%, 50.4%);
  }
}
```

What did you expect to happen?

Not give a fatal parsing exception. This issue is the same as #642 except the keyframes have commas

What actually happened? Please include any error messages given to you by Sass Lint.

> 83:1  error  Please check validity of the block starting from line #83  Fatal

**Comment by bgriffith** [comment]
hey @megawac - as far as I am aware, the code above is invalid due to the comma.

I ran it through both the [css validator](https://jigsaw.w3.org/css-validator/validator) and [sassmeister](http://www.sassmeister.com)

**Comment by megawac** [comment]
node-sass strips the commas in this case. The output after node-sass runs is

```css
@keyframes enroute {
  0% {
    transform: translate(-50%, 50%); }
  
  100% {
    transform: translate(-50%, 50.4%); } }
```

Not sure if the code works in the browser - I was just linting some code from a third part and noticed this error
