### ISSUE TITLE
Is it possible to only allow hex colors in variable declarations?

### ISSUE THREAD

**Issue by benjamincharity** [sasstools/sass-lint#987]
With SCSS-lint I was able to define rules that colors such as `red` or `#bada55` can **not** be used in a style declaration, but **can** be used in a variable declaration.  Is there a way to replicate that behavior with this tool? ([scss-lint rule](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#colorvariable))

### Desired functionality

```scss
// Disallowed
.foo {
  background: #C0FF33;
  color: red;
}

// Allowed
$my_background: #FA113D;
$my_color: mistyrose;

.bar {
  background-color: $my_background;
  color: $my_color;
}
```

What version of Sass Lint are you using? `1.10.1`
